/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AsymTrace.app.factory;

import AsymTrace.app.model.ContactMessage;
import AsymTrace.app.model.ContactInfo;
import com.goterl.lazycode.lazysodium.LazySodium;
import com.goterl.lazycode.lazysodium.interfaces.Box;
import com.goterl.lazycode.lazysodium.utils.Key;


public class ContactInfoFactory {

    LazySodium lazySodium;

    public ContactInfoFactory(LazySodium lazySodium) {
        this.lazySodium = lazySodium;
    }

    public ContactInfo fromContactMessage(ContactMessage contactMessage, Key haPrivateKey) {

        byte[] cipherText = contactMessage.getHaCiphertext();
        byte[] contactData = new byte[cipherText.length - Box.MACBYTES];
        byte[] nonce = contactMessage.getHaNonce();

        boolean success = lazySodium.cryptoBoxOpenEasy(
                contactData,
                cipherText,
                cipherText.length,
                nonce,
                contactMessage.getContactPublicKeyBytes(),
                haPrivateKey.getAsBytes()
        );

        if (success) {
            return new ContactInfo(contactData, contactMessage.getAdditionalData());
        }
        return null;

    }

}
