/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AsymTrace.app.factory;

import AsymTrace.app.model.AccessUploadMessage;
import com.goterl.lazycode.lazysodium.LazySodium;
import com.goterl.lazycode.lazysodium.LazySodiumJava;
import com.goterl.lazycode.lazysodium.SodiumJava;
import com.goterl.lazycode.lazysodium.exceptions.SodiumException;
import com.goterl.lazycode.lazysodium.utils.Key;
import com.goterl.lazycode.lazysodium.utils.KeyPair;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;



public class AccessUploadMessageTest {

    @Test
    public void testSuccessfullCreationAndDecryption() throws SodiumException {

        LazySodium lazySodium = new LazySodiumJava(new SodiumJava("/Library/Frameworks/libsodium.dylib"));

        KeyPair kp = lazySodium.cryptoBoxKeypair();

        Key secretBytes = lazySodium.cryptoSecretBoxKeygen();

        AccessUploadMessage accessUploadMessage = new AccessUploadMessageFactory(lazySodium).create(kp.getPublicKey(), secretBytes);
        assertNotNull(accessUploadMessage);

        Key secretKeyOut = new AccessUploadMessageFactory(lazySodium).decrypt(accessUploadMessage, kp);

        assertNotNull(secretKeyOut);
        assertArrayEquals(secretBytes.getAsBytes(), secretKeyOut.getAsBytes());
    }
}
