/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AsymTrace.app.factory;

import AsymTrace.app.model.ContactMessage;
import AsymTrace.app.model.ContactInfo;
import AsymTrace.app.model.Identity;
import com.goterl.lazycode.lazysodium.LazySodium;
import com.goterl.lazycode.lazysodium.LazySodiumJava;
import com.goterl.lazycode.lazysodium.SodiumJava;
import com.goterl.lazycode.lazysodium.exceptions.SodiumException;
import com.goterl.lazycode.lazysodium.utils.KeyPair;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


public class ContactMessageTest {

    @Test
    public void testConversion() throws SodiumException {

        LazySodium lazySodium = new LazySodiumJava(new SodiumJava("/Library/Frameworks/libsodium.dylib"));


        KeyPair kp = lazySodium.cryptoBoxKeypair();
        KeyPair haKp = lazySodium.cryptoBoxKeypair();

        byte[] contactData = new byte[5];
        byte[] visibleData = new byte[5];

        Identity id = new Identity(kp, contactData, visibleData);

        ContactMessage contactMessage = new ContactMessageFactory(lazySodium).fromIdentity(id, haKp.getPublicKey());
        assertNotNull(contactMessage);

        ContactInfo contactInfo = new ContactInfoFactory(lazySodium).fromContactMessage(contactMessage, haKp.getSecretKey());
        assertNotNull(contactInfo);

        assertArrayEquals(id.getContactData(), contactInfo.getContactData());
        assertArrayEquals(id.getDisplayData(), contactInfo.getAdditionalData());
    }
}
