/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AsymTrace.app;

import AsymTrace.app.utils.ByteArrayListUtil;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ByteArrayListUtilTest {
    @Test
    public void testRandom() {

        Random r = new Random(42);

        // num elements
        for (int i = 0; i < 6; i++) {

            List<byte[]> input = new ArrayList<>();

            for (int k = 0; k < i; k++) {
                int l = r.nextInt(20);
                byte[] b = new byte[l];
                r.nextBytes(b);
                input.add(b);
            }


            List<byte[]> output = ByteArrayListUtil.split(
                    ByteArrayListUtil.merge(input)
            );

            assertEquals(input.size(), output.size());

            for (int k = 0; k < i; k++) {
                assertEquals(input.get(k).length, output.get(k).length);
                assertArrayEquals(input.get(k), output.get(k));
            }
        }
    }
}
